/**
 * 用户可见的标准界面文案。
 *
 * 分类顺序为：领域 → 场景或组件 → 语义名称。单次且强依赖页面上下文的
 * 完整句保留在组件内；用户作品内容、Agent 指令和服务端日志不属于这里。
 */
export const uiCopy = {
  api: {
    error: {
      localServiceUnavailable: "本地服务暂时不可用。",
    },
  },
  common: {
    action: {
      back: "返回",
      cancel: "取消",
      close: "关闭",
      collapse: "收起",
      confirmCancel: "确认取消",
      confirmDelete: "确认删除",
      confirmImport: "确认导入",
      confirmMerge: "确认合并",
      confirmRemove: "确认移除",
      confirmSave: "确认保存",
      confirmSplit: "确认拆分",
      createContent: "创作",
      delete: "删除",
      discard: "丢弃",
      download: "下载图片",
      edit: "修改",
      editName: "修改名称",
      enterWorkbench: "进入工作台",
      expand: "展开",
      more: "更多选项",
      preview: "预览",
      reload: "重新加载",
      reconnect: "重新连接",
      renameImage: "修改图片名称",
      retry: "重试",
      save: "保存",
      saveDetails: "保存资料",
      goToSettings: "前往设置",
      view: "查看",
      viewImage: "查看图片",
      removeFromCanvas: "从画布移除",
    },
    progress: {
      creating: "正在创建…",
      copyingPlain: "复制中",
      processing: "处理中…",
      deletingPlain: "删除中",
      deleting: "删除中…",
      downloading: "下载中…",
      savingPlain: "保存中",
      saving: "保存中…",
      uploadingPlain: "上传中",
      uploading: "上传中…",
    },
    status: {
      notConfigured: "未配置",
      saveFailed: "保存失败",
      comingSoon: "即将开放",
    },
    navigation: {
      backToHomeAria: "返回 Lantern 首页",
      globalSettings: "全局设置",
      globalEntry: "全局入口",
    },
    field: {
      description: "描述",
      name: "名称",
      title: "标题",
    },
  },
  metadata: {
    applicationName: "Lantern AI",
    defaultTitle: "Lantern AI · 漫画创作工作台",
    libraryTitle: "我的漫画",
    comicTitle: "漫画详情",
    workbenchTitle: "漫画工作台",
    previewTitle: "漫画阅读预览",
    titleTemplate: (title: string) => `${title} · Lantern AI`,
  },
  brand: {
    api: "LANTERN API",
    name: "Lantern AI",
    preview: "LANTERN PREVIEW",
    visualAssets: "VISUAL ASSETS",
    wordmark: {
      primary: "Lantern",
      accent: "AI",
    },
  },
  eyebrow: {
    newComic: "NEW COMIC",
    newAsset: "NEW ASSET",
    globalSettings: "GLOBAL SETTINGS",
  },
  toast: {
    common: {
      cancelFailed: "取消失败",
      firstPage: "已经是第一页",
      lastPage: "已经是最后一页",
      renameFailed: "重命名失败",
      retryFailed: "重试失败",
      saveFailed: "保存失败",
    },
    assetSpace: {
      loadFailed: "资产暂时无法读取",
      created: (name: string) => `已创建资产「${name}」`,
      importedToCanvas: (name: string) => `已将「${name}」导入当前画布资产列表`,
      importFailed: "导入画布资产列表失败，请稍后重试",
      briefUpdated: (title: string) => `已更新「${title}」`,
      visualStyleImageUploaded: "视觉风格图片已上传",
      detailsUpdated: (name: string) => `已更新「${name}」的资产资料`,
      deleted: (name: string) => `已删除资产「${name}」`,
    },
    comicOverview: {
      settings: {
        comicSaved: (status: string) => `漫画设置已保存，当前为${status}`,
        chapterSaved: (status: string) => `本话设置已保存，当前为${status}`,
      },
      upload: {
        imageTooLarge: "图片太大，请换一张小图",
        invalidFormat: "请选择 PNG、JPEG 或 WebP",
        failed: "上传失败，请换一张图片再试",
      },
      deletion: {
        stopRunningTask: "请先停止运行中的任务",
        serviceUnavailable: "本地服务暂时不可用",
        failed: "删除失败，请稍后再试",
        chapterDeleted: "已删除这一话",
        comicDeleted: "已删除漫画",
      },
      duplication: {
        completed: "已复制为一部全新的漫画",
        failed: "复制漫画失败，请稍后再试",
      },
    },
    preview: {
      firstChapter: "已经是第一话",
      pageDownloadStarted: (pageNumbers: string) => `第 ${pageNumbers} 页已开始下载`,
      chapterImagesDownloadStarted: "本话图片 ZIP 已开始下载",
      chapterImagesDownloadFailed: "本话图片 ZIP 下载失败，请稍后重试",
      downloadFailed: "保存失败，请稍后重试",
      lcdDownloadStarted: "LCD 已开始下载",
      archiveDownloadStarted: "完整 LCD 资源已开始下载",
      archiveDownloadFailed: "完整 LCD 资源下载失败，请稍后重试",
      demoExportUnsupported: "演示模式暂不支持导出，请切换到服务端模式后重试",
      demoArchiveExportUnsupported: "演示模式暂不支持完整资源导出，请切换到服务端模式后重试",
    },
    workbench: {
      assetCreation: {
        readyForAgent: "已将资产资料填入对话，可继续补充后发送",
      },
      archive: {
        demoImportUnsupported: "演示模式暂不支持导入完整 LCD 资源",
        stopTaskBeforeImport: "请先等待或停止当前 Agent 任务，再导入完整 LCD 资源",
        imported: (revision: number) => `已导入完整 LCD 资源 · r${revision}`,
        importFailed: "完整 LCD 资源导入失败",
      },
      session: {
        stopTaskBeforeSwitch: "请先停止当前任务，再切换对话",
        switched: "已切换对话",
        switchFailed: "对话切换失败",
        createNameRequired: "请先填写对话名称",
        offlineCreated: "已创建新的离线对话",
        created: "新对话已创建",
        createFailed: "创建对话失败",
        renameNameRequired: "请填写对话名称",
        renamed: "对话已重命名",
        stopTaskBeforeDelete: "请先停止当前任务，再删除对话",
        deleted: "对话已删除",
        deleteFailed: "删除对话失败",
      },
      draft: {
        restoring: "正在回到上次保存，请稍候",
        revisionConflict: "工作稿已变化，请重新操作",
        changeNotApplied: "变更未应用，旧内容保持不变",
        persisting: (label: string) => `${label} · 正在保存`,
        persisted: (label: string, revision: number) => `${label} · 工作稿 r${revision}`,
        reloadedAfterError: (message: string) => `${message}，已重新载入工作稿`,
        persistenceFailed: "保存工作稿失败，已重新载入工作稿",
        invalidCapabilityInput: "编辑参数无效",
      },
      editing: {
        addFrameFailed: "无法新增画格",
        duplicateFrameFailed: "无法复制画格",
        replaceImageFirst: "请先移除当前图片，再重新放入",
        placeImageFailed: "无法放入图片",
        addDialogueFailed: "无法新增对白",
        addPaperDialogueFailed: "无法新增纸面对白",
        addNarrationFailed: "无法新增旁白",
        duplicateDialogueFailed: "无法复制对白",
        duplicateNarrationFailed: "无法复制旁白",
        frameTitleRequired: "请先填写分镜标题",
        invalidBorderWidth: "请输入有效的边框粗细",
        selectFrame: "请选择一个画格",
      },
      layout: {
        breakoutEnabled: "已设为破格 · 对象仍随原画格移动",
        crossPageCanceled: (objectName: string) => `已取消跨页 · ${objectName}已归入单一纸面`,
        crossSegmentCanceled: "已取消跨段 · 图片已归入单一滚动段",
        convertedToPaperImage: "已转为纸面图片 · 使用独立图片编号",
        convertedToPaperDialogue: "已转为纸面对白",
        returnedToFrame: "已收回画格 · 恢复画格裁切",
        overlapEnabled: "已允许叠格 · 当前画格已置于顶层",
        overlapDisabled: "已恢复画格不可重叠",
        crossPageFrameEnabled: "已设为跨页格 · 可跨越双页中缝移动和缩放",
        crossPageFrameDisabled: "已取消跨页 · 画格已归入单一纸面",
        bleedEnabled: (edge: string) => `已延伸至${edge}侧页边`,
        bleedDisabled: (edge: string) => `已恢复${edge}侧边框`,
        pageStructureFailed: "无法改变页面结构",
      },
      image: {
        downloadUnavailable: "当前图片资源不可下载",
        downloadStarted: "图片已开始下载",
        downloadFailed: "图片下载失败，请稍后重试",
        viewUnavailable: "当前图片资源不可查看",
        alreadyInAssetList: "该图片已添加到资产列表",
        addedToAssetList: "已添加到资产列表",
        addToAssetListFailed: "添加到资产列表失败",
        cardSaveFailed: "图片卡片状态保存失败",
        assetImageSwitched: (label: string) => `已切换为「${label}」`,
        assetImageSwitchFailed: "资产图片切换失败",
      },
      mode: {
        cropExited: "已退出裁切模式",
        cropEntered: "已进入裁切模式：拖动图片调整取景，拖动画格四角调整角度",
        cornerEditEntered: "已进入画格四角编辑：拖动顶点调整边线角度",
        moveExited: "已退出移动模式",
        moveEntered: "已进入移动模式：拖动对象调整位置",
        balloonRotationEntered: "已进入气泡旋转模式：拖动右下角编辑点旋转",
        narrationRotationEntered: "已进入旁白旋转模式：拖动右下角编辑点旋转",
        cropUnsupported: "当前对象不支持裁切或四角编辑",
        focusCanvas: "聚焦模式 · 页面回到画面中心",
        freeCanvas: "自由模式 · 拖动画布查看图片和页面",
        viewportDisabled: "设备视区已关闭",
        viewportEnabled: (label: string) => `设备视区 · ${label}`,
        multiSelectEntered: "已进入多选模式",
      },
      history: {
        undone: (label: string) => `已撤销：${label}`,
        redone: (label: string) => `已重做：${label}`,
      },
      agent: {
        taskUnavailable: "暂不支持这项 Agent 任务",
        taskAlreadyRunning: "当前会话已有任务运行中，请先等待或取消",
        selectCurrentFrame: "请先选择当前工作稿中的漫画格",
        demoOffline: "离线演示不连接 Agent 服务",
        taskCreateFailed: "任务创建失败",
        imageUploading: "图片仍在上传，请稍候",
        imageUploadFailed: "有图片上传失败，请移除后重新添加",
        unavailable: "Agent 暂时不可用",
        attachmentLimit: "一轮对话最多添加 3 张图片",
        attachmentUploadFailed: "图片附件上传失败",
      },
      candidate: {
        cannotApplyEnded: "该候选已结束，不能重复应用",
        applyFailed: "候选应用失败",
        stale: "候选基于旧工作稿，需要重新生成",
        noApplicableContent: "该候选没有可应用内容",
        cannotPreviewEnded: "该候选已结束，不能继续预览",
        targetMissing: "候选目标已不在当前工作稿中",
        wrongPage: (pageLabel: string) => `该候选属于 ${pageLabel}，请切换到目标页后再预览`,
        previewFailed: "候选图片暂时无法预览",
        previewTargetChanged: "预览目标已经变化，请重新打开该候选",
        discardFailed: "候选丢弃失败",
      },
      snapshot: {
        saved: (revision: number) => `一话已保存 · 快照 r${revision}`,
        draftChanged: "工作稿已变化，请重新保存",
        restored: (revision: number) => `已回到保存版本 r${revision}`,
        restoreFailed: "无法回到上次保存",
      },
      canvas: {
        objectDeleted: "画布对象已删除；资产库内容保持不变",
        objectDeleteFailed: "删除画布对象失败",
        elementsMoved: (count: number) => `已移动 ${count} 个画布元素`,
        moveElementsFailed: "批量移动画布元素失败",
        elementsRemoved: (count: number) => `已从画布移除 ${count} 个元素；资产库内容保持不变`,
        removeElementsFailed: "批量移除画布元素失败",
      },
      reference: {
        assetVersionMissing: "该资产还没有可引用的版本",
        canvasAssetVersionMissing: "该画布图片还没有可引用的资产版本",
      },
      asset: {
        imageAddedToCanvasAndList: "图片已加入画布和资产列表",
        imageSavedRefreshFailed: (message: string) => `图片已保存，刷新列表失败：${message}`,
        imageSavedRefreshFallback: "图片已保存，刷新列表失败，请刷新页面",
        imageSaveFailed: "图片保存失败，请重试",
        confirmedImageMissing: "该资产还没有可用图片，请先生成或上传一个版本",
        placedOnCanvas: (name: string) => `「${name}」已放到画布图片层`,
        placementFailed: "资产放置失败",
        imageNotInCanvasList: "请先将这张图片添加到画布资产列表，再保存到资产空间",
        savedToSpace: "已保存到资产空间",
        saveToSpaceFailed: "保存到资产空间失败",
        pinned: (name: string) => `已置顶「${name}」`,
        pinFailed: "置顶失败",
        removedFromList: (name: string) => `已从列表移除「${name}」`,
        removeFromListFailed: "从列表移除失败",
        renamed: (name: string) => `当前画布中的名称已改为「${name}」`,
        imageUnavailable: (name: string) => `「${name}」还没有可查看的图片`,
      },
      message: {
        cardStateSaveFailed: "卡片状态保存失败",
      },
    },
  },
  landing: {
    hero: {
      aria: "Lantern AI",
      subtitle: "续写旧作篇章，新建故事企划，打造独属于你的漫画世界",
      tagline: "一盏灯，陪你打磨漫画故事",
      start: "开始创作",
      scrollToLibrary: "向下滚动，进入我的漫画",
    },
    demo: {
      comicAria: "漫画创作示例",
      storyboardAlt: "漫画分镜编辑示意图",
      selectedLastFrameAria: "已选中最后一个画格",
      frameToolbarAria: "画格工具栏",
      aiToolbarAria: "AI 创作工具",
      cropFrameAria: "裁切画格",
      editFrameAria: "编辑画格",
      taskCardAria: "创作任务卡片",
      toolsAria: "创作工具示例",
      selectToolAria: "选择工具",
      moveToolAria: "移动工具",
      arrangeToolAria: "编排工具",
      modeSwitchAria: "创作与预览模式",
      creationModeAria: "当前为创作模式",
    },
  },
  library: {
    hero: {
      currentWorkspace: "当前创作空间",
    },
    navigation: {
      listAria: "漫画列表",
      newComicAria: "新建漫画",
    },
    action: {
      createComic: "创建漫画",
      loadMore: "加载更多漫画",
    },
    progress: {
      loadingMore: "正在加载…",
    },
    error: {
      createFailed: "创建漫画失败",
      listLoadFailed: "漫画列表暂时无法加载",
      moreLoadFailed: "更多漫画暂时无法加载",
    },
    empty: {
      chapterPrompt: "先新建一话",
      creationTitle: "开始一个新故事",
    },
    form: {
      descriptionPlaceholder: "简单介绍这部漫画的故事、角色或氛围",
      pageFormatHint: "适合分页阅读",
      structureLabel: "漫画结构",
      verticalFormatHint: "适合纵向滚动",
    },
    cover: {
      missingAria: "尚未设置漫画封面",
      comicAlt: (title: string) => `${title}漫画封面`,
    },
    badge: {
      exampleComic: "示例漫画",
    },
    summary: {
      empty: "还没有故事简介。",
      chapterCount: (count: number) => `查看章节 · ${count} 话`,
    },
  },
  comic: {
    eyebrow: {
      settings: "COMIC SETTINGS",
      chapterSettings: "CHAPTER SETTINGS",
      newChapter: "NEW CHAPTER",
    },
    readingDirection: {
      leftToRight: "从左到右",
      rightToLeft: "从右到左",
    },
    format: {
      fourPanel: "四格",
      page: "页漫",
      vertical: "条漫",
    },
    creationStatus: {
      complete: "已完成",
      creating: "创作中",
    },
    unit: {
      page: "漫画页",
      segment: "滚动段",
    },
    field: {
      description: "漫画简介",
      name: "漫画名称",
    },
    action: {
      readingPreview: "阅读预览",
    },
    overview: {
      error: {
        createChapterFailed: "创建新一话失败",
        loadFailed: "漫画信息暂时无法加载",
        saveChapterFailed: "保存章节设置失败",
        saveComicFailed: "保存漫画设置失败",
      },
      progress: {
        loading: "正在加载漫画…",
      },
      navigation: {
        backToLibraryAria: "返回我的漫画",
        openAssetsAria: "进入资产空间",
      },
      action: {
        openSettings: "漫画设置",
        newChapter: "新建一话",
        saveSettings: "保存设置",
        createChapter: "创建并进入工作台",
        changeChapterCoverAria: "更换本话封面",
        duplicateComic: "复制漫画",
        deleteComic: "删除漫画",
        deleteChapter: "删除一话",
      },
      section: {
        chapters: "章节",
        chapterSettings: "修改设置",
      },
      field: {
        creationStage: "创作阶段",
        readingOrder: "阅读顺序",
        chapterSummary: "本话梗概",
      },
      cover: {
        changeHint: "点击更换封面",
        uploadHint: "点击上传封面",
        chapterAlt: (number: number) => `第 ${number} 话封面`,
      },
      chapter: {
        defaultTitle: (number: number) => `第 ${number} 话`,
        numberLabel: (number: number) => `第 ${number} 话`,
        moreAria: (number: number) => `第 ${number} 话更多选项`,
        waiting: "等待第一话",
      },
      aria: {
        exampleStatus: "漫画创作阶段（示例漫画不可修改）",
        status: "漫画创作阶段",
        chapterStatus: "章节创作阶段",
      },
      deletion: {
        comicTitle: (title: string) => `删除漫画“${title}”？`,
        chapterTitle: (number: number, title: string) => `删除“第 ${number} 话 · ${title}”？`,
        comicDescription: "漫画和其中所有章节会从当前创作空间中移除。",
        chapterDescription: "这一话会从漫画中移除，其他章节和漫画资料保持不变。",
      },
    },
  },
  asset: {
    eyebrow: {
      detail: (kind: string) => `${kind} ASSET`,
      visualStyle: "VISUAL STYLE",
      storyCore: "STORY CORE",
      world: "WORLD",
      space: "ASSET SPACE",
      creativeBaseline: "CREATIVE BASELINE",
    },
    navigation: {
      space: "资产空间",
    },
    kind: {
      character: "角色",
      image: "图片",
      prop: "道具",
      scene: "场景",
      sketch: "草图",
      style: "风格",
    },
    kindTag: {
      character: "人",
      scene: "景",
      prop: "物",
      style: "风",
      sketch: "草",
    },
    label: {
      asset: "资产",
      content: "内容",
      variant: "形态",
      type: "资产类型",
    },
    action: {
      addCharacter: "添加角色",
      addImage: "添加图片",
      addProp: "添加道具",
      addScene: "添加场景",
      addToList: "添加到资产列表",
      changeImage: "更换图片",
      saveToLibrary: "保存为资产",
      referenceInChat: "引用到对话",
      restore: "还原",
      importToCanvasList: "导入当前画布列表",
    },
    aria: {
      importToCanvasList: (name: string) => `将${name}导入当前画布列表`,
      editBrief: (title: string) => `编辑${title}`,
      briefContent: (title: string) => `${title}内容`,
    },
    status: {
      addedToList: "已添加到资产列表",
      linked: "已关联资产",
    },
    image: {
      listAria: "图片列表",
      label: "图片名称",
      supportedFormats: "PNG、JPEG 或 WebP",
      emptyTitle: "还没有资产图片",
      emptyDescription: "文字资料仍然可以用于创作。",
      primary: "主图",
      previous: "上一张图片",
      next: "下一张图片",
      editUnavailable: "暂不支持 AI 图片精修",
      deleteTitle: "删除这张图片？",
      coverAlt: (name: string) => `${name}资产封面`,
      viewerAria: (name: string) => `${name}图片查看器`,
      viewAria: (label: string) => `查看${label}`,
    },
    page: {
      allFilter: "全部",
      baselineTitle: "创作基线",
      baselineLoadingAria: "正在读取创作基线",
      organizing: "正在整理资产…",
      visualAssetsTitle: "视觉资产",
      visualAssetsHint: "填写资料并按需上传图片",
    },
    baseline: {
      visualStyle: {
        title: "视觉风格",
        description: "统一管理线条、色彩、光影、构图规则和风格图片。",
        placeholder: "描述线条、色彩、媒介质感、镜头语言和希望避免的风格。",
      },
      storyCore: {
        title: "故事核心",
        description: "这部漫画最重要的故事承诺与核心冲突。",
        placeholder: "用一两段话说明主角、目标、冲突与故事吸引力。",
      },
      worldSetting: {
        title: "世界设定",
        description: "跨章节保持一致的时代背景、规则与长期冲突。",
        placeholder: "补充世界规则、时代背景、地域、组织或超自然机制。",
      },
    },
    detail: {
      emptyContent: "暂无内容",
      emptyDescription: "暂无描述",
      loadingAria: "正在加载资产详情",
      loadFailedAria: "资产详情加载失败",
      closeAria: "关闭资产详情",
      opening: "正在打开资产…",
      unavailable: "资产详情暂时无法读取",
      nameLabel: "资产名称",
      editNameHint: "双击编辑资产名称",
      variantsAria: "资产派生形态",
      editCopyAria: "编辑资产文字资料",
      descriptionLabel: "详细描述",
      copyAria: "资产文字资料",
      editAria: "编辑资产资料",
      uploadImageAria: "上传资产图片",
      delete: "删除资产",
      currentPrimary: "当前主图",
      setPrimary: "设置为主图",
      deleteTitle: (name: string) => `删除资产“${name}”？`,
      variantCount: (count: number) => `共 ${count} 个形态`,
      renameImageDescription: "名称用于区分同一资产中的不同图片。",
      deleteImageDescription: "图片会从当前资产中移除，已经放到画布上的内容不会被打断。",
      deleteWithVariantsDescription: (count: number) => `资产及其 ${count} 个派生形态会从资产空间和画布资产列表移除，已经放到页面或画布上的内容不会被打断。`,
      deleteDescription: "资产会从资产空间和画布资产列表移除，已经放到页面或画布上的内容不会被打断。",
    },
    visualStyle: {
      uploadImageAria: "上传视觉风格图片",
      renameImageDescription: "名称用于区分不同的视觉风格图片。",
      deleteImageDescription: "图片会从视觉风格中移除。",
    },
    error: {
      detailLoadFailed: "资产详情暂时无法读取。",
      upload: "图片上传失败，请稍后重试。",
      delete: "图片删除失败，请稍后重试。",
      nameEmpty: "图片名称不能为空。",
      nameSave: "图片名称保存失败，请稍后重试。",
      download: "图片下载失败，请稍后重试。",
      attachmentUpload: "图片附件上传失败",
      genericUpload: "上传失败",
      visualStyleImageMissing: "视觉风格图片不存在。",
      detailsSave: "资产资料保存失败，请稍后重试。",
      assetNameEmpty: "资产名称不能为空。",
      assetNameSave: "资产名称保存失败，请稍后重试。",
      setPrimary: "主图设置失败，请稍后重试。",
      assetDelete: "资产删除失败，请稍后重试。",
      briefSave: "保存失败，请稍后重试。",
      visualStyleUpload: "视觉风格图片上传失败",
      coverUpload: "上传封面失败",
      fileTooLarge: "图片文件太大，请上传 50MB 以内的 PNG、JPEG 或 WebP。",
      invalidFormat: "请选择 PNG、JPEG/JPG 或 WebP 图片。",
      uploadChannelRejected: "上传通道暂时拒绝了这张图片，请稍后重试；不需要更换图片。",
    },
    create: {
      aiAria: "交给 AI 创建",
      aiUnavailable: "暂时无法进入对话，请稍后重试。",
      closeAria: "关闭创建资产",
      creating: "创建中…",
      description: "填写基础资料；图片可选，之后也能在资产详情中继续添加。",
      descriptionPlaceholder: "记录外观、用途、性格或在故事中的作用",
      failed: "创建资产失败，请稍后重试。",
      imageAddedAsPrimary: "创建后会作为首张图片上传",
      imageOptionalHint: "可选，支持 PNG、JPG、WebP",
      imagePickerEmpty: "添加一张图片",
      imagePickerReplace: "重新选择",
      imagePickerSelect: "选择图片",
      namePlaceholder: "填写一个便于识别的名称",
      submit: "创建资产",
      title: "添加资产",
      chapterRequired: "请先新建一话，再交给 AI 创建资产。",
      intent: {
        character: "创建一个角色",
        scene: "创建一个场景",
        prop: "创建一个道具",
        reference: "我想添加一张图片",
        asset: "创建一个新资产",
      },
      agentPrompt: (kind: string, name?: string, description?: string) => [
        `创建一个${kind}：`,
        name ? `名称：${name}` : "",
        description ? `描述：${description}` : "",
      ].filter(Boolean).join("\n"),
    },
  },
  workbench: {
    versions: {
      entryAria: "历史版本与草稿",
      panelAria: "历史版本与草稿列表",
      title: "历史版本与草稿",
      type: {
        current: "当前版本",
        saved: "正式版本",
        proposal: "方案稿",
      },
      newProposal: "新增",
      currentHint: "当前版本，无法进入对比",
      empty: "还没有保存版本或方案。",
      closeAria: "收起历史版本与草稿",
      loadFailed: "版本列表暂时无法载入。",
      openComparison: (label: string) => `对比${label}`,
      compareTitle: "版本对比",
      noDifference: "当前展示单元无差异",
      hasDifference: "当前展示单元有差异",
      added: "当前展示单元为新增",
      removed: "当前展示单元不存在",
      previousDifference: "上一个差异",
      nextDifference: "下一个差异",
      previousUnit: "上一个展示单元",
      nextUnit: "下一个展示单元",
      applyAndSave: "应用并保存",
      retain: "保留方案",
      discard: "丢弃方案",
      discardConfirmTitle: "丢弃这个方案？",
      confirmDiscard: "丢弃这个方案？正式工作稿不会改变。",
      staleApplyConfirmTitle: "当前版本已发生变化",
      confirmStaleApply: "此方案基于较早的版本。应用后将以方案内容覆盖当前工作稿，并创建新的当前版本和正式版本。",
      restore: "回退到此版本",
      restoreConfirmTitle: "回退到此版本？",
      confirmRestore: "复制此版本的内容，创建一个新的当前版本和正式版本？原有版本不会被删除。",
      deleteVersion: "删除版本",
      deleteVersionConfirmTitle: "删除这个版本？",
      confirmDeleteVersion: "将永久删除这个正式版本；不再被任何版本、画布或资产引用的图片也会一并清理。",
      stale: "当前版本已发生变化，应用方案可能会覆盖当前修改",
      actionFailed: "版本操作失败，请重试。",
      loading: "正在载入版本对比",
      backAria: "返回漫画工作台",
    },
    selection: {
      none: "未选择对象",
    },
    balloonStyle: {
      dialogue: "对话气泡",
      noTail: "无尾气泡",
      cutCorner: "切角对白",
      box: "方框对白",
      thought: "思考气泡",
      shout: "喊叫气泡",
      whisper: "低语气泡",
      electronic: "电子气泡",
      tremble: "颤抖气泡",
    },
    defaultLabel: {
      currentObject: "当前对象",
      currentChapter: "当前一话",
      loading: "正在载入",
      newFrame: "新画格",
      frameCopy: "画格副本",
      newDialogue: "新对白",
      paperDialogue: "纸面对白",
      dialogueCopy: "对白副本",
      framePrimaryImage: "格内主图",
      frameImage: "画格图片",
      paperImage: "纸面图片",
      paperImageShort: "纸面图",
      object: "对象",
      comicImage: "漫画图片",
    },
    defaultDescription: {
      restoredCanvasAsset: "从漫画画布恢复的图片资产",
      uploadedImage: "手动上传图片",
    },
    scope: {
      balloon: "当前气泡",
      comicFrame: "当前漫画格",
      currentFrame: "当前画格",
      currentPage: "当前页面",
      frameImageCrop: "格内图片裁切",
      imageOnly: "仅图片",
      narration: "当前旁白",
      currentComicAssets: "当前漫画资产",
    },
    object: {
      dialogue: "对白",
      frame: "画格",
      image: "图",
      paper: "纸面",
      crossPage: "跨页",
      crossPageFrame: "跨页格",
      crossPageImage: "跨页图片",
      crossPageBalloon: "跨页对白",
      crossSegment: "跨段",
      crossSegmentImage: "跨段图片",
      insideFrame: "格内",
      breakout: "破格",
    },
    taskStage: {
      preparing: "正在准备上下文",
      queued: "等待生成资源",
      generating: "模型生成中",
      validating: "正在校验结果",
      saving: "正在保存候选",
    },
    taskLabel: {
      generateAssetImage: "生成资产图片",
    },
    action: {
      editStoryboard: "编辑分镜条目",
      createStoryboard: "创建单格画面",
      editFrameImage: "编辑单格画面",
      generateFrameImage: "生成单格画面",
      replaceFrameImage: "更换格内图片",
      placeFrameImage: "放入格内图片",
      cancelCrossPage: "取消跨页",
      cancelCrossSegment: "取消跨段",
      returnToSaved: "回到上次保存",
      saveVersion: "保存版本",
      moveFrame: "移动画格",
      rotateBalloon: "旋转对白气泡",
      rotateNarration: "旋转旁白",
      layer: "层级",
      moveToFront: "置于顶层",
      moveToBack: "置于底层",
      moveLayerUp: "上移一层",
      moveLayerDown: "下移一层",
      zoomIn: "放大",
      zoomOut: "缩小",
      addFrame: "新增画格",
      duplicateFrame: "复制画格",
      deleteFrame: "删除画格",
      placeCrossPageImage: "设为跨页图片",
      placeCrossSegmentImage: "设为跨段图片",
      placeCrossPageBalloon: "设为跨页对白",
      addDialogue: "新增对白",
      addPaperDialogue: "新增纸面对白",
      duplicateDialogue: "复制对白",
      deleteDialogue: "删除对白",
      duplicateNarration: "复制旁白",
      deleteNarration: "删除旁白",
      enableBreakout: "设为破格",
      convertToPaperImage: "转为纸面图片",
      convertToPaperDialogue: "转为纸面对白",
      returnToFrame: "收回画格",
      enableCrossPageFrame: "设为跨页格",
      insertPageBefore: "向前插入一页",
      insertPageAfter: "向后插入一页",
      duplicateCurrentPage: "复制当前页",
      addStoryPage: "正文页",
      addCoverPage: "封面页",
      addInterludePage: "过场页",
      movePageUp: "上移一页",
      movePageDown: "下移一页",
      splitSegment: "拆分滚动段",
      mergeNextPage: "合并下一页",
      splitToSinglePages: "拆分为单页",
      mergeNextSegment: "与下一段合并",
      locateOnCanvas: "定位到画布",
      addToCanvas: "添加到画布",
      pin: "置顶",
      removeFromList: "从列表移除",
      editPage: "编辑页",
      cancelOverlap: "取消叠格",
      allowOverlap: "允许叠格",
      extendToPageEdge: "延伸至页边",
      backgroundColor: "背景颜色",
      white: "白色",
      black: "黑色",
      removeImage: "移除图片",
      horizontal: "转为横向",
      vertical: "转为竖向",
      addInProgress: "添加中…",
      viewCurrentContext: "查看当前上下文",
      importArchive: "导入完整 LCD 资源",
      importingArchive: "正在导入完整 LCD…",
    },
    operation: {
      addNarration: "新增旁白",
      addVerticalSegment: (aspectRatio: string) => `新增滚动段 ${aspectRatio}`,
      allowFrameOverlap: "允许画格重叠并置于顶层",
      forbidFrameOverlap: "禁止画格重叠",
      cancelFrameCrossPage: "取消画格跨页",
      toggleFrameBleed: (enabled: boolean, edge: string) => `${enabled ? "开启" : "取消"}${edge}边出血`,
      setPageBackground: (color: string) => `设置页面背景为${color}`,
      editBalloon: "编辑对白与气泡样式",
      editNarration: "编辑旁白",
      adjustBalloonStyle: "调整对白气泡样式",
      adjustFrameBorder: "调整画格边框",
      adjustImageCrop: "调整图片裁切",
      moveComicElements: (count: number) => `已移动 ${count} 个漫画元素`,
      removeFrameImage: "移除格内图片",
      removeCrossPageImage: "移除跨页图片",
      removeCrossSegmentImage: "移除跨段图片",
      removePaperImage: "移除纸面图片",
      moveObjectToFront: "对象置于顶层",
      moveObjectToBack: "对象置于底层",
      moveFrameToFront: "画格置于顶层",
      moveFrameToBack: "画格置于底层",
      deleteCanvasObject: "删除画布对象",
      moveCanvasElements: (count: number) => `已移动 ${count} 个画布元素`,
      removeCanvasElements: (count: number) => `已从画布移除 ${count} 个元素`,
      moveCanvasImage: (name: string) => `移动图片「${name}」`,
      zoomCanvasImage: (name: string) => `缩放图片「${name}」`,
      movedToFront: "已置于顶层",
      movedToBack: "已置于底层",
      movedLayerUp: "已上移一层",
      movedLayerDown: "已下移一层",
      uploadImage: "上传图片",
      uploadedCanvasImageDetail: "手动上传 · 画布图片",
      uploadToCanvasAndAssets: "上传图片到资产列表与画布",
      mergeSpread: "合并为真正双页",
      splitSpread: "拆分真正双页",
      mergeSegments: "合并滚动段",
      undo: (label: string) => `撤销：${label}`,
      redo: (label: string) => `重做：${label}`,
      applyCandidate: (title: string) => `应用候选「${title}」`,
      placeAssetOnCanvas: (name: string) => `把「${name}」放到画布图片层`,
      editUnit: (name: string) => `编辑「${name}」`,
      deleteUnit: (name: string) => `删除「${name}」`,
      horizontalDialogue: "转为横向对白",
      verticalDialogue: "转为竖向对白",
      horizontalNarration: "转为横向旁白",
      verticalNarration: "转为竖向旁白",
    },
    menuGroup: {
      add: "新增",
      frameLayout: "画格布局",
      crossPage: "跨页",
      crossSegment: "跨段",
      ownership: "归属",
      more: "更多",
    },
    direction: {
      top: "上",
      right: "右",
      bottom: "下",
      left: "左",
    },
    bleed: {
      action: (mode: "cancel" | "extend", edge: string) => `${mode === "cancel" ? "取消" : "延伸至"}${edge}侧页边`,
    },
    label: {
      page: (value: number | string) => `Page ${value}`,
      pageTag: (value: number | string) => `PAGE ${value}`,
      pageRangeTag: (value: string) => `PAGES ${value}`,
      fourPanelTag: "4-KOMA 01",
      frame: (order: number | string) => `画格 ${String(order).padStart(2, "0")}`,
      dialogue: (order: number | string) => `对白 ${String(order).padStart(2, "0")}`,
      narration: (order: number | string) => `旁白 ${String(order).padStart(2, "0")}`,
      frameFinal: (order: number | string) => `画格 ${String(order).padStart(2, "0")} · 格内成稿`,
      frameCrop: (label: string) => `${label} · 格内图片裁切`,
      currentPageImage: (kind: string, order: number) => `当前页 · ${kind} ${String(order).padStart(2, "0")}`,
      canvasImage: (name: string) => `画布 · ${name}`,
      crossSegmentCount: (count: number) => `跨 ${count} 段`,
      pageUnit: "页",
      segmentUnit: "段",
      spreadUnit: "双页",
      pageFrameStatus: (count: number, current: boolean) => `${count} 格 · ${current ? "当前查看" : "工作稿"}`,
      segment: (value: number | string) => `滚动段 ${value}`,
      fourPanel: (value: number | string) => `四格 ${value}`,
      viewport: (label: string) => `设备视区：${label}`,
    },
    aria: {
      increment: (label: string, step: number) => `${label}增加${step}`,
      decrement: (label: string, step: number) => `${label}减少${step}`,
      assetMore: (name: string) => `${name}更多选项`,
      pageMore: (name: string) => `${name}更多选项`,
      candidateImage: (title: string) => `查看${title}图片`,
      candidatePreview: (title: string) => `${title}预览`,
      manageConversation: (title: string) => `管理「${title}」`,
      viewAttachment: (name: string) => `查看${name}`,
      attachmentReference: (name: string) => `${name} 对话引用`,
      attachmentPending: (name: string) => `${name} 待发送`,
      cancelAttachmentReference: (name: string) => `取消引用${name}`,
      referenceThumbnail: (label: string) => `${label} 缩略图`,
      switchViewport: (label: string) => `${label}，点击切换`,
      editUnit: (unit: string) => `编辑${unit}`,
      deletePage: (name: string) => `删除“${name}”？`,
    },
    panel: {
      creationSpace: "创作空间",
    },
    page: {
      loadFailed: "工作台暂时无法载入",
      loadingDraft: "正在载入工作稿",
    },
    navigation: {
      backToComic: "返回漫画",
      backToHome: "返回首页",
      projectMenuAria: "打开项目菜单",
      projectSubtitle: (comic: string, chapter: string, revision: number, mode: "server" | "demo" | "other") => `${comic} · ${chapter} · r${revision}${mode === "server" ? " · 已持久化" : mode === "demo" ? " · 离线演示" : ""}`,
      loadingBrand: "LANTERN WORKBENCH",
    },
    creationSpace: {
      collapseAria: "收起创作空间",
      categoriesAria: "创作空间分类",
      uploadAssetAria: "上传图片资产并放到画布",
      cancelRenameAria: "取消重命名",
      frameSectionTitle: "单格画面",
      emptyFrame: "未填写单格内容",
      storyboardTab: "分镜",
      emptyAssets: "还没有可用资产。",
      emptyFrames: "当前页面还没有画格。",
    },
    pageFlow: {
      addSegment: "新增滚动段",
      addPageAria: "新增漫画页",
      addPageMenuAria: "选择新增页面类型",
      coverAlreadyExists: "本话已有封面页，已定位到封面页",
      pageRole: {
        cover: "封面",
        interlude: "过场",
      },
      virtualPageAria: "在此翻页",
      createVirtualPageAria: "将虚拟补位变成实际页面",
      movePageToVirtualSlot: "移动页面到此补位",
      pageThumbnailAlt: "漫画页缩略图",
      blankPageAria: "空白漫画页",
      expandAria: "展开创作流",
      closeCardAria: "关闭页面卡片",
      cropBottomHint: "（裁切页面底部）",
      freeModePaginationAria: "自由模式翻页",
      mergeSpreadTitle: "与下一页合并为真正双页？",
      splitSpreadTitle: "拆分为两个单页？",
      mergeSegmentTitle: "与下一段合并为跨段画布？",
      splitSegmentTitle: "拆分为独立滚动段？",
      pageRatio: "页面比例",
      pageRatioAria: "滚动段页面比例",
      ratioWouldCrop: "页面下方空间不足，现有画格会被裁切，无法应用该比例",
      defaultSegment: "滚动段 01",
    },
    task: {
      cancelAria: "取消任务",
      failed: "生成失败",
      failedLabel: "任务失败",
      cancelTitle: "取消当前任务？",
      currentScope: "当前创作范围",
      unchanged: "工作稿未改变",
      cancelledMessage: "任务已取消，没有产生可应用结果。",
    },
    candidate: {
      saveToAsset: "保存到资产",
      apply: "应用",
      previewToolbarAria: "候选图片预览工具栏",
      pending: "待应用",
      saved: "已保存",
      applied: "已应用",
      reverted: "已回退",
      expired: "已过期",
      discarded: "已丢弃",
      noFramePreview: "这个候选没有可预览的单格画面",
      stalePreview: "候选基于旧工作稿，无法继续预览",
      editStoryboard: (label: string) => `编辑分镜条目 · ${label}`,
      appliedMessage: (title: string) => `「${title}」已作为一次原子变更进入工作稿。如需回退，请使用底部撤销。`,
    },
    saveAssetDialog: {
      cancelAria: "取消保存为资产",
      typeLabel: "类型",
      description: (name: string) => `将“${name}”保存到资产空间`,
    },
    segmentDialog: {
      ratioAria: "选择滚动段比例",
      ratioLabel: "宽 : 高",
    },
    objectEditor: {
      toolbarAria: "对象编辑工具栏",
      referenceAria: "将当前对象引用到 Agent 对话",
      toggleBalloonTransformAria: "开启或关闭气泡移动、缩放和尖尾调整",
      toggleNarrationTransformAria: "开启或关闭旁白移动和换行宽度调整",
      togglePaperImageTransformAria: "开启或关闭纸面图片移动和缩放",
      toggleFrameMoveAria: "开启或关闭移动画格",
      cropFrameImageAria: "裁切格内图片并调整画格角度",
      cropPaperImageAria: "裁切纸面图片",
      editBalloonAria: "编辑对白和气泡样式",
      editNarrationAria: "编辑旁白文字和字号",
      manageAria: "管理当前对象",
      closeAria: "关闭对象编辑器",
      manageMenuAria: "对象管理菜单",
      selectBleedEdgeAria: "选择出血边",
    },
    frameEditor: {
      closeAria: "关闭画格编辑",
      storyboardTitle: "分镜条目",
      titlePlaceholder: "分镜标题",
      descriptionPlaceholder: "描述这一格的场景、人物、动作、情绪或叙事作用",
      createAndBind: "创建并绑定",
      borderWidthLabel: "边框粗细",
      borderWidthAria: "画格边框粗细",
      saveBorder: "保存边框",
      moveLeft: "左移",
      moveUp: "上移",
      moveDown: "下移",
      moveRight: "右移",
      resetCrop: "重置取景",
      resetRotation: "重置画格角度",
      backToFrame: "回到画格",
      editTitle: (label: string) => `编辑画格 · ${label}`,
    },
    imagePicker: {
      moreAria: "图片更多选项",
      selectAria: "选择漫画图片",
      placeCrossPage: "放入跨页图片",
      placeCrossSegment: "放入跨段图片",
      placePaper: "放入纸面图片",
      replaceCrossPage: "更换跨页图片",
      replaceCrossSegment: "更换跨段图片",
      replacePaper: "更换纸面图片",
      replaceBreakout: "更换破格图片",
      sourceHint: "选择当前页、画布或资产中的图片",
      assetSourceHint: "选择左侧资产列表中的图片",
      closeAria: "关闭图片选择",
      uploadToFrameAria: "上传图片并放入当前画格",
      switchAssetImageTitle: "切换资产图片",
      empty: "资产列表还没有图片，可在这里上传",
    },
    reference: {
      cardAria: (name: string, kind: string) => `${name}，${kind}，仅作为画布图片`,
      imageAlt: (name: string) => `${name}图片`,
      switchImageAria: (name: string) => `切换${name}的资产图片`,
    },
    balloonEditor: {
      closeAria: "关闭对白编辑",
      textStyleLabel: "文字样式",
      fontSizeLabel: "字号",
      fontSizeAria: "对话字号",
      borderWidthAria: "气泡边框粗细",
    },
    narrationEditor: {
      closeAria: "关闭旁白编辑",
      textLabel: "文字",
      fontSizeAria: "旁白字号",
      placementPreview: "请输入文本",
    },
    chat: {
      panelAria: "Agent 对话",
      sessionsAria: "打开当前画布的会话列表",
      collapseAria: "收起 Agent 工作区",
      currentSessionsAria: "当前画布会话",
      currentCanvasLabel: "当前画布",
      newSessionAria: "新建会话",
      sessionNamePlaceholder: "输入新对话名称",
      createSessionAria: "创建会话",
      cancelNewSessionAria: "取消新建会话",
      saveSessionNameAria: "保存会话名称",
      rename: "重命名",
      thinkingAria: "Agent 正在思考",
      expandAria: "展开 Agent 工作区",
      internalAgentHint: "内置 Agent 迭代中，推荐使用 MCP + Skills！",
      referenceLabel: "引用",
      newConversationTitle: "新的创作对话",
      uploadedReferences: (count: number) => `上传了 ${count} 张图片作为本轮参考。`,
      offlineDemo: "离线演示只提供画布操作；连接本地服务后可使用创作对话。",
      editStoryboardPrompt: "编辑选中画格的分镜条目，只改标题和画面描述",
      initialGuide: "可以直接和我讨论漫画内容；选择画格后可以创建或编辑该格的分镜条目，也可以直接描述要创建的资产图片。",
    },
    composer: {
      queuedPlaceholder: "可以继续准备下一条消息；任务结束后再发送",
      placeholder: "描述你想让 AI 生成、修改或确认的内容…",
      addReferenceAria: "添加对话引用或 Agent 选项",
      referenceCurrentAria: "引用当前对象",
      taskRunningAria: "任务运行中",
      imageUploadingAria: "图片上传中",
      sendAria: "发送",
    },
    toolbar: {
      creationAria: "创作工具",
      focusModeAria: "聚焦选择模式",
      freeModeAria: "自由拖动画布",
      uploadCanvasImageAria: "上传图片到画布图片层",
      cancelNarrationAria: "取消放置旁白",
      placeNarrationAria: "在纸面放置旁白",
      undoAria: "撤销",
      redoAria: "重做",
      saveVersionAria: "保存当前工作稿为正式版本",
      aiEditStoryboardAria: "AI 编辑选中画格的分镜条目",
      previewAria: "切换到阅读预览",
      previewDisabledTitle: "请先保存当前一话，再进入阅读预览",
    },
    multiSelect: {
      toolbarAria: "多选工具",
      referenceAria: "将选中对象引用到对话",
      disableComicAria: "暂时取消选中的漫画元素",
      enableComicAria: "重新选中漫画元素",
      disableCanvasAria: "暂时取消选中的画布元素",
      enableCanvasAria: "重新选中画布元素",
      moveAria: "批量移动选中对象",
      removeAria: "从画布批量移除选中对象",
      exitAria: "退出多选模式",
    },
    contextDebug: {
      title: "当前上下文",
      eyebrow: "DEVELOPMENT · LIVE SNAPSHOT",
      page: (number: number) => `Page ${String(number).padStart(2, "0")}`,
      closeAria: "关闭上下文调试",
      navigationAria: "上下文定位目录",
      copyAria: "复制当前内容",
      refreshAria: "重新计算上下文",
      rawJsonAria: "当前上下文原始 JSON",
      offline: "当前处于离线演示模式，无法读取服务端上下文。",
      loadFailed: "读取当前上下文失败",
      loading: "正在重新读取数据库并构建上下文…",
      waiting: "等待上下文快照…",
      currentConversation: "当前对话",
      workingRevision: (revision: number) => `工作稿 r${revision}`,
      snapshotLabel: "完整可复制快照",
      currentInstruction: (type: string) => `当前指令 · ${type || "未指定"}`,
      longTermSetting: "漫画级长期设定",
      emptySetting: "尚未填写",
      assetCount: (count: number) => `${count} 个上下文资产`,
      storyboardCount: (count: number) => `${count} 个实际送入模型`,
      pageCount: (count: number) => `${count} 页工作稿`,
      recentActivity: "候选、任务、最近消息",
      section: {
        rawJson: "原始 JSON",
        inputAndFocus: "输入与焦点",
        worldBackground: "世界观背景",
        castAndScenes: "角色与场景",
        tasksAndSessions: "任务与会话",
      },
    },
    error: {
      apiUnavailable: "无法连接 Lantern API",
      agentStreamIncomplete: "Agent 流式响应未正常结束。",
      archiveDownload: "完整 LCD 资源下载失败",
      archiveDownloadRetry: "完整 LCD 资源下载失败，请稍后重试。",
      archiveImport: "完整 LCD 导入失败",
      archiveImportRetry: "完整 LCD 导入失败，请稍后重试。",
      archiveInvalidFormat: "请选择 Lantern 导出的 ZIP 完整 LCD 归档。",
      archiveTooLarge: "完整 LCD 归档必须小于 512MB。",
    },
    dialog: {
      overwriteChapterTitle: "覆盖当前一话内容？",
      saveVersionTitle: "保存当前工作稿？",
      saveVersionDescription: "把当前工作稿保存为新的正式版本。原有正式版本和方案稿会继续保留。",
      configureModelTitle: "配置模型后继续",
      removeTitle: (label: string) => `移除“${label}”？`,
      deleteTitle: (label: string) => `删除“${label}”？`,
      frameDeleteDescription: (count: number) => `画格中的 ${count} 个图片或对白元素会从页面移除。关联分镜会保留为未编排内容。`,
      emptyFrameDeleteDescription: "这是一个空画格。关联分镜会保留为未编排内容。",
      imageDeleteDescription: (location: "cross_page" | "cross_segment" | "paper" | "frame") => `${location === "cross_page" ? "跨页图片会从当前双页中移除" : location === "cross_segment" ? "跨段图片会从当前复合滚动段中移除" : location === "paper" ? "图片会从当前纸面中移除" : "图片会从当前画格中移除"}，资产库中的原图和其他引用保持不变。`,
      narrationDeleteDescription: "旁白文字会从当前页面中移除。该操作可以撤销。",
      balloonDeleteDescription: (location: string) => `对白文字和对应气泡会从${location}中移除。`,
      keepOneUnit: "漫画至少需要保留一个展示单元，当前内容不能删除。",
      unitDeleteDescription: (surfaceCount: number, surfaceKind: "page" | "segment", frameCount: number) => `${surfaceCount > 1 ? `其中 ${surfaceCount} 个物理${surfaceKind === "page" ? "页" : "段"}和` : "其中"}${frameCount} 个画格会一并移除。该操作可以撤销。`,
      mergePagesDescription: "两张物理页会成为一个不可拆开的双页展示单元，原有对象与页码会保留。",
      mergeSegmentsDescription: "两个物理段会成为一个连续编辑单元，可放入单个跨段图片。",
      splitDescription: "仅当画格和对象都没有跨越分隔线时才能安全拆分。",
      cancelTaskDescription: "任务会立即停止，当前工作稿不会改变，也不会产生新的候选结果。",
      importArchiveDescription: (name: string) => `导入「${name}」会把完整 LCD、分镜条目和图片资源写入当前一话，并保存为新的稳定版本。现有历史版本不会删除。`,
      configureModelDescription: "当前 AI 能力还没有可用的 API Key。画布编辑不受影响，配置完成后可以直接重试。",
      imageInspectorDescription: "拖动图片调整取景，滚轮或下面动作缩放；拖动画格四角可沿横向或纵向调整边线角度。",
    },
  },
  viewer: {
    action: {
      fitWindow: "适应窗口",
      nextPage: "下一页",
      previousPage: "上一页",
      singlePage: "切换为单页模式",
      spread: "切换为双页模式",
    },
  },
  imageViewer: {
    closeAria: "关闭图片查看器",
    unavailable: "图片暂时无法显示",
    toolbarAria: "图片查看工具",
    zoomOutAria: "缩小图片",
    zoomInAria: "放大图片",
    originalSizeAria: "按原始尺寸查看",
    originalSizeTitle: "1:1 原始尺寸",
  },
  renderer: {
    empty: "暂无可预览的漫画页面",
    frameImageAlt: "漫画画格中的格内成稿图",
    framePrimaryImage: (label: string) => `${label}主图`,
    frameBalloon: (label: string) => `${label}气泡`,
    frameBreakoutBalloon: (label: string) => `${label}破格气泡`,
    pageImage: "页面图像",
    paperBalloon: "纸面气泡",
    pageBalloon: "页面气泡",
    narration: (order: number) => `旁白 ${String(order).padStart(2, "0")}`,
    pageSelection: (order: number) => `Page ${String(order).padStart(2, "0")}`,
    watermark: {
      scroll: (order: number) => `SCROLL ${String(order).padStart(2, "0")}`,
      fourPanel: "4-KOMA",
      page: (order: number) => `PAGE ${String(order).padStart(2, "0")}`,
    },
    waitingFrameImageAria: "等待格内成稿图",
    cropImage: "调整图片取景",
    zoomImageCrop: "缩放图片取景",
    movePaperImage: "移动纸面图片",
    resizePaperImage: "调整纸面图片大小",
    rotateFrame: "调整画格角度",
    resizeFrame: "调整画格大小",
    resizeNarration: "调整旁白宽度",
    moveNarration: "移动旁白",
    resizeBalloon: "调整气泡大小",
    moveBalloon: "移动对话气泡",
    adjustBalloonTail: "调整气泡尾巴长度与指向",
    cornerAria: {
      topLeft: "左上",
      topRight: "右上",
      bottomRight: "右下",
      bottomLeft: "左下",
    },
    selectFrameAria: (label: string) => `选择${label}`,
    selectObjectAria: (label: string) => `选择${label}`,
    adjustCornerAria: (corner: string) => `调整画格${corner}角；使用方向键单轴微调`,
  },
  viewport: {
    disabled: "设备视区已关闭",
    phone: "手机 9:16",
    tallPhone: "长屏手机 9:20",
    tablet: "平板 3:4",
  },
  preview: {
    page: {
      loadFailed: "预览暂时无法载入",
      loadingSavedVersion: "正在载入已保存版本",
      noSavedVersion: "还没有已保存版本",
      noSavedVersionDescription: "请先返回工作台保存当前一话，再进入阅读预览。",
    },
    action: {
      backToWorkbench: "返回工作台",
      downloadSpread: "下载当前双页",
      downloadPage: "下载当前页",
      downloadChapterImages: "下载本话图片（ZIP）",
      downloadLcd: "下载 LCD 文件",
      downloadFullLcd: "下载完整 LCD 资源",
    },
    toolbar: {
      previewAria: "预览工具",
      modeSwitchAria: "模式切换",
      creationModeAria: "回到创作模式",
      currentModeAria: "当前为预览模式",
      downloadOptionsAria: "下载选项",
    },
    progress: {
      preparingDownload: "准备下载…",
    },
    error: {
      download: "下载失败，请稍后重试。",
      noPage: "当前没有可下载的漫画页。",
      noSurface: "当前没有可下载的物理纸面。",
      noSpread: "当前没有可下载的双页预览。",
    },
  },
  settings: {
    page: {
      loading: "正在载入设置…",
    },
    apiKey: {
      label: "API Key",
      configuredAria: "API Key 已配置",
      placeholder: "输入 API Key",
      managedByEnvironment: "这项配置由启动环境变量管理。",
    },
    field: {
      provider: "提供方",
      model: "模型",
      apiUrl: "API 地址",
      providerAria: (label: string) => `${label}提供方`,
    },
    error: {
      heading: "无法载入设置",
      loadFailed: "设置载入失败",
    },
    section: {
      modelApi: "模型 API",
      externalAgentGuideUrl: "https://github.com/lanseqingling/lantern#%E9%80%9A%E8%BF%87-mcp-%E4%B8%8E-skill-%E6%8E%A5%E5%85%A5%E5%A4%96%E7%BD%AE-agent",
      localRuntime: "本地运行",
      updates: "应用更新",
    },
    update: {
      checking: "正在检查更新…",
      currentLabel: "当前版本",
      available: (current: string, latest: string) => `v${current} → v${latest}`,
      check: "检查更新",
      download: "下载更新",
      openRelease: "打开 Lantern Release",
      checkAria: "检查 Lantern 更新",
      preparing: "正在下载并准备更新…",
      downloading: (progress: number) => `正在下载更新… ${progress}%`,
      verifying: "正在校验更新…",
      extracting: "正在解压更新…",
      stopping: "正在停止 Lantern…",
      replacing: "正在安装更新…",
      restarting: "正在更新并重新启动…",
      progressAria: "Lantern 更新进度",
      failed: "更新失败，请重试",
    },
    runtime: {
      dataDirectory: "数据目录",
      localPorts: "本地端口",
      objectStorage: "对象存储",
    },
  },
  tour: {
    workbench: {
      stepsAria: "工作台导览步骤",
      previousAria: "上一步",
      finishAria: "完成导览",
      nextAria: "下一步",
      finish: "完成",
      replayAria: "播放工作台导览",
      stepTitle: {
        canvasControls: "选择与拖动画布",
        historyAndSave: "撤销、重做与保存",
        pageDisplay: "页面显示",
        creationAndPreview: "创作与预览",
        agentCollaboration: "与 Agent 协作",
      },
      stepContent: {
        creationSpace: "在资产与分镜之间切换，整理当前一话的创作素材。",
        comicPages: "切换、添加和管理漫画页；条漫会在这里显示滚动段。",
        focusMode: "聚焦模式编辑对象。",
        freeMode: "自由模式移动画布。",
        undo: "撤销上一步画布编辑。",
        redo: "重做刚刚撤销的编辑。",
        saveVersion: "把当前工作稿保存为新的正式版本。",
        pageDisplay: "页漫切换单双页；条漫切换设备视区。",
        creationMode: "创作模式编辑漫画。",
        previewMode: "预览模式检查最终画面。",
        versionHistory: "查看正式版本和 Agent 方案，对比差异后应用、保留、丢弃或回退。",
        agentComposer: "选择对象后，在这里描述要生成、修改或确认的内容。",
      },
    },
  },
} as const;
