import {
  AtSign,
  ArrowDown,
  ArrowUp,
  BookOpen,
  BookOpenCheck,
  Braces,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleHelp,
  Copy,
  Crop,
  Download,
  FileText,
  FileUp,
  Folder,
  Hand,
  History,
  Home,
  Image,
  Images,
  LayoutDashboard,
  LayoutGrid,
  Layers3,
  ListTree,
  Menu,
  MessageCircle,
  MessageSquareText,
  MapPin,
  MoreHorizontal,
  MoreVertical,
  MousePointer2,
  Move,
  Network,
  Package,
  PanelRightClose,
  PanelsTopLeft,
  Pencil,
  Pin,
  Plus,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Save,
  Scan,
  SendHorizontal,
  Settings,
  Sparkles,
  SquareMousePointer,
  Trash2,
  Type,
  UserRound,
  X,
  ZoomIn,
  ZoomOut,
} from "lucide-react";
import {
  ComicFormatFourPanelIcon,
  ComicFormatPageIcon,
  ComicFormatVerticalIcon,
  PageSingleIcon,
  PageSpreadIcon,
  ProjectMenuIcon,
  WorkbenchCompactIcon,
  WorkbenchIcon,
} from "./custom";
import type { IconDefinition, IconGlyph } from "./types";

function icon(defaultGlyph: IconGlyph, options: Omit<IconDefinition, "default"> = {}): IconDefinition {
  return { default: defaultGlyph, ...options };
}

export const iconRegistry = {
  select: icon(MousePointer2),
  pan: icon(Hand),
  asset: icon(Images),
  assetAll: icon(LayoutGrid),
  scene: icon(MapPin),
  prop: icon(Package),
  referenceImage: icon(Image),
  home: icon(Home),
  folder: icon(Folder),
  comic: icon(BookOpen),
  workbench: icon(WorkbenchIcon, { compact: WorkbenchCompactIcon }),
  mcpConnection: icon(Network),
  layout: icon(LayoutGrid),
  layers: icon(Layers3),
  text: icon(Type),
  lettering: icon(MessageSquareText),
  ai: icon(Sparkles),
  preview: icon(BookOpenCheck),
  undo: icon(RotateCcw),
  redo: icon(RotateCw),
  more: icon(MoreHorizontal),
  moreVertical: icon(MoreVertical),
  save: icon(Save),
  send: icon(SendHorizontal),
  close: icon(X),
  collapse: icon(ChevronLeft),
  expand: icon(ChevronRight),
  move: icon(Move),
  crop: icon(Crop),
  replace: icon(RefreshCw),
  reference: icon(AtSign),
  edit: icon(Pencil),
  hamburger: icon(Menu),
  projectMenu: icon(ProjectMenuIcon, { strokeWidth: 2 }),
  download: icon(Download),
  publish: icon(FileUp),
  add: icon(Plus),
  moveUp: icon(ArrowUp),
  moveDown: icon(ArrowDown),
  chevronDown: icon(ChevronDown),
  chevronUp: icon(ChevronUp),
  panelRightClose: icon(PanelRightClose),
  creationSpaceOpen: icon(LayoutDashboard),
  storyboard: icon(PanelsTopLeft),
  pages: icon(FileText),
  pageSingle: icon(PageSingleIcon),
  pageSpread: icon(PageSpreadIcon),
  pointer: icon(SquareMousePointer),
  pin: icon(Pin),
  message: icon(MessageCircle),
  agentActivity: icon(ListTree),
  delete: icon(Trash2),
  user: icon(UserRound),
  settings: icon(Settings),
  comicSettings: icon(Settings),
  help: icon(CircleHelp),
  history: icon(History),
  zoomIn: icon(ZoomIn),
  zoomOut: icon(ZoomOut),
  scan: icon(Scan),
  context: icon(Braces),
  copy: icon(Copy),
  comicFormatPage: icon(ComicFormatPageIcon, { strokeWidth: 1.8 }),
  comicFormatVertical: icon(ComicFormatVerticalIcon, { strokeWidth: 1.8 }),
  comicFormatFourPanel: icon(ComicFormatFourPanelIcon, { strokeWidth: 1.8 }),
} satisfies Record<string, IconDefinition>;

export type IconName = keyof typeof iconRegistry;
export const iconNames = Object.freeze(Object.keys(iconRegistry) as IconName[]);
